# Generated by Django 2.0.1 on 2020-09-08 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geocode', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='employee_location',
            name='emp_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.EmployeeModel'),
        ),
    ]
