# Generated by Django 2.0.1 on 2020-09-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='address',
            new_name='ADDRESS',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='city',
            new_name='CITY',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='name',
            new_name='NAME',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='state',
            new_name='STATE',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='zipcode',
            new_name='ZIPCODE',
        ),
    ]
