# Generated by Django 2.0.1 on 2020-09-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200908_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='ADDRESS',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='CITY',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='STATE',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='employeemodel',
            old_name='ZIPCODE',
            new_name='zipcode',
        ),
    ]
