# Generated by Django 2.0.1 on 2020-09-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200908_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_location',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee_location',
            name='emp_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel'),
        ),
    ]
