# Generated by Django 2.0.1 on 2020-09-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200908_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceAustin',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_austin',
            },
        ),
        migrations.CreateModel(
            name='DistanceBoston',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_boston',
            },
        ),
        migrations.CreateModel(
            name='DistanceChicago',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_chicago',
            },
        ),
        migrations.CreateModel(
            name='DistanceColumbus',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_columbus',
            },
        ),
        migrations.CreateModel(
            name='DistanceDallas',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_dallas',
            },
        ),
        migrations.CreateModel(
            name='DistanceHouston',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_houston',
            },
        ),
        migrations.CreateModel(
            name='DistanceLosAngeles',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_los_angeles',
            },
        ),
        migrations.CreateModel(
            name='DistanceNewYork',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_new_york',
            },
        ),
        migrations.CreateModel(
            name='DistancePhoenix',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_phoenix',
            },
        ),
        migrations.CreateModel(
            name='DistanceSanDiego',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_san_diego',
            },
        ),
        migrations.CreateModel(
            name='DistanceSanJose',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app1.EmployeeModel')),
                ('distance', models.FloatField()),
            ],
            options={
                'verbose_name': 'dist_san_jose',
            },
        ),
    ]
